name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  # Every Monday at 2:50pm UTC
  schedule:
    - cron: '50 14 * * 1'

jobs:
  ci:
    name: CI
    # Only run cron on my account
    if: (github.event_name == 'schedule' && github.repository_owner == 'guysartorelli') || (github.event_name != 'schedule')
    uses: silverstripe/gha-ci/.github/workflows/ci.yml@v1
